import { Router } from 'express';
import authRoutes from './auth.routes.js';
import healthRoutes from './health.routes.js';
import cartRoutes from './cart.routes.js';
import couponRoutes from './coupon.routes.js';
import orderRoutes from './order.routes.js';
import categoryRoutes from './category.routes.js';
import productRoutes from './product.routes.js';
import paymentRoutes from './payment.routes.js';
import pushRoutes from './push.routes.js';
import adminRoutes from './admin.routes.js';
import bannerRoutes from './banner.routes.js';
import storeSettingsRoutes from './storeSettings.routes.js';
import homepageSectionRoutes from './homepageSection.routes.js';
import favoriteRoutes from './favorite.routes.js';
import reviewRoutes from './review.routes.js';
import loyaltyRoutes from './loyalty.routes.js';
import walletRoutes from './wallet.routes.js';
import deliveryZoneRoutes from './deliveryZone.routes.js';
import searchRoutes from './search.routes.js';
import contentPageRoutes from './contentPage.routes.js';
import sitemapRoutes from './sitemap.routes.js';
import notificationTemplateRoutes from './notificationTemplate.routes.js';
import brandRoutes from './brand.routes.js';
import promotionRoutes from './promotion.routes.js';
import fulfillmentLocationRoutes from './fulfillmentLocation.routes.js';
import userNotificationRoutes from './userNotification.routes.js';
import assistantRoutes from './assistant.routes.js';
import supportRoutes from './support.routes.js';
import supportChatRoutes from './supportChat.routes.js';
import whatsappRoutes from './whatsapp.routes.js';

const router = Router();

router.use('/health', healthRoutes);
router.use('/auth', authRoutes);
router.use('/cart', cartRoutes);
router.use('/coupons', couponRoutes);
router.use('/orders', orderRoutes);
router.use('/categories', categoryRoutes);
router.use('/products', productRoutes);
router.use('/payment', paymentRoutes);
router.use('/payments', paymentRoutes);
router.use('/admin', adminRoutes);
router.use('/banners', bannerRoutes);
router.use('/store-settings', storeSettingsRoutes);
router.use('/homepage-sections', homepageSectionRoutes);
router.use('/favorites', favoriteRoutes);
router.use('/reviews', reviewRoutes);
router.use('/loyalty', loyaltyRoutes);
router.use('/wallet', walletRoutes);
router.use('/delivery-zones', deliveryZoneRoutes);
router.use('/search', searchRoutes);
router.use('/content-pages', contentPageRoutes);
router.use('/sitemap', sitemapRoutes);
router.use('/notification-templates', notificationTemplateRoutes);
router.use('/brands', brandRoutes);
router.use('/promotions', promotionRoutes);
router.use('/fulfillment-locations', fulfillmentLocationRoutes);
router.use('/my-notifications', userNotificationRoutes);
router.use('/push', pushRoutes);
router.use('/assistant', assistantRoutes);
router.use('/support', supportRoutes);
router.use('/support-chat', supportChatRoutes);
router.use('/whatsapp', whatsappRoutes);

export default router;
