export const SEED_CATEGORIES = [
  { slug: 'fruits-vegetables', nameAr: 'فواكه وخضروات', nameEn: 'Fruits & Vegetables', icon: '🥬', color: 'bg-green-100', sortOrder: 1 },
  { slug: 'dairy', nameAr: 'ألبان وجبن', nameEn: 'Dairy & Cheese', icon: '🥛', color: 'bg-blue-100', sortOrder: 2 },
  { slug: 'bakery', nameAr: 'مخبوزات', nameEn: 'Bakery', icon: '🍞', color: 'bg-amber-100', sortOrder: 3 },
  { slug: 'meat-poultry', nameAr: 'لحوم ودواجن', nameEn: 'Meat & Poultry', icon: '🥩', color: 'bg-red-100', sortOrder: 4 },
  { slug: 'beverages', nameAr: 'مشروبات', nameEn: 'Beverages', icon: '🥤', color: 'bg-cyan-100', sortOrder: 5 },
  { slug: 'snacks', nameAr: 'سناكس وحلويات', nameEn: 'Snacks & Sweets', icon: '🍫', color: 'bg-orange-100', sortOrder: 6 },
  { slug: 'cleaning', nameAr: 'منظفات', nameEn: 'Cleaning', icon: '🧹', color: 'bg-purple-100', sortOrder: 7 },
  { slug: 'personal-care', nameAr: 'عناية شخصية', nameEn: 'Personal Care', icon: '🧴', color: 'bg-pink-100', sortOrder: 8 },
  { slug: 'baby', nameAr: 'مستلزمات الأطفال', nameEn: 'Baby Products', icon: '👶', color: 'bg-yellow-100', sortOrder: 9 },
  { slug: 'electronics', nameAr: 'إلكترونيات', nameEn: 'Electronics', icon: '📱', color: 'bg-slate-100', sortOrder: 10 },
  { slug: 'frozen', nameAr: 'مجمدات', nameEn: 'Frozen Foods', icon: '🧊', color: 'bg-sky-100', sortOrder: 11 },
  { slug: 'household', nameAr: 'منتجات منزلية', nameEn: 'Household', icon: '🏠', color: 'bg-teal-100', sortOrder: 12 },
];

export const SEED_COUPONS = [
  {
    code: 'FIRST20',
    discountType: 'percent',
    discountValue: 20,
    minSubtotal: 100,
    expiryDate: new Date('2027-12-31'),
    usageLimit: 1000,
    labelAr: 'خصم 20%',
    labelEn: '20% off',
  },
  {
    code: 'SAVE50',
    discountType: 'fixed',
    discountValue: 50,
    minSubtotal: 300,
    expiryDate: new Date('2027-12-31'),
    usageLimit: 500,
    labelAr: 'خصم 50 ج.م',
    labelEn: '50 EGP off',
  },
  {
    code: 'FREESHIP',
    discountType: 'free_delivery',
    discountValue: 0,
    minSubtotal: 0,
    expiryDate: new Date('2027-12-31'),
    usageLimit: null,
    labelAr: 'توصيل مجاني',
    labelEn: 'Free delivery',
  },
];

export const SEED_BANNERS = [
  // Hero carousel — full-width slides (Carrefour-style homepage)
  {
    titleAr: 'عروض متتفوتش',
    titleEn: 'Unmissable Deals',
    subtitleAr: 'خصومات تصل إلى 50% على آلاف المنتجات',
    subtitleEn: 'Up to 50% off on thousands of products',
    image: 'https://placehold.co/1200x400/059669/ffffff?text=MarketPlus+Offers',
    link: '/offers',
    placement: 'hero',
    sortOrder: 1,
  },
  {
    titleAr: 'توصيل سريع',
    titleEn: 'Fast Delivery',
    subtitleAr: 'اطلب الآن واستلم خلال ساعتين',
    subtitleEn: 'Order now, get it in 2 hours',
    image: 'https://placehold.co/1200x400/047857/ffffff?text=Express+Delivery',
    link: '/products',
    placement: 'hero',
    sortOrder: 2,
  },
  {
    titleAr: 'خضار وفواكه طازجة',
    titleEn: 'Fresh Produce',
    subtitleAr: 'من المزرعة إلى بابك يومياً',
    subtitleEn: 'Farm fresh, delivered daily',
    image: 'https://placehold.co/1200x400/10b981/ffffff?text=Fresh+Produce',
    link: '/categories/fruits-vegetables',
    placement: 'hero',
    sortOrder: 3,
  },
  // Promo row — three cards under hero
  {
    titleAr: 'منتجات طازجة',
    titleEn: 'Fresh Products',
    subtitleAr: 'فواكه وخضروات يومياً',
    subtitleEn: 'Daily fruits & vegetables',
    image: 'https://placehold.co/600x200/10b981/ffffff?text=Fresh',
    link: '/categories/fruits-vegetables',
    placement: 'promo',
    sortOrder: 1,
  },
  {
    titleAr: 'عروض الألبان',
    titleEn: 'Dairy Deals',
    subtitleAr: 'خصم على الألبان والجبن',
    subtitleEn: 'Discounts on milk & cheese',
    image: 'https://placehold.co/600x200/3b82f6/ffffff?text=Dairy',
    link: '/categories/dairy',
    placement: 'promo',
    sortOrder: 2,
  },
  {
    titleAr: 'مشروبات باردة',
    titleEn: 'Cold Drinks',
    subtitleAr: 'عروض المشروبات والعصائر',
    subtitleEn: 'Beverages & juice offers',
    image: 'https://placehold.co/600x200/06b6d4/ffffff?text=Beverages',
    link: '/categories/beverages',
    placement: 'promo',
    sortOrder: 3,
  },
];

export const SEED_PRODUCTS = [
  { slug: 'fresh-tomatoes-1kg', nameAr: 'طماطم طازجة', nameEn: 'Fresh Tomatoes', price: 18.99, oldPrice: 24.99, categorySlug: 'fruits-vegetables', emoji: '🍅', unit: '1 كجم', rating: 4.5, stock: 100, isOffer: true, isFeatured: true },
  { slug: 'eggs-large-30', nameAr: 'بيض بلدي كبير', nameEn: 'Large Local Eggs', price: 89.99, oldPrice: 99.99, categorySlug: 'dairy', emoji: '🥚', unit: '30 بيضة', rating: 4.8, stock: 50, isOffer: true, isFeatured: true },
  { slug: 'full-cream-milk-1l', nameAr: 'لبن كامل الدسم', nameEn: 'Full Cream Milk', price: 32.5, oldPrice: null, categorySlug: 'dairy', emoji: '🥛', unit: '1 لتر', rating: 4.6, stock: 200, isOffer: false, isFeatured: true },
  { slug: 'white-bread-loaf', nameAr: 'عيش فينو أبيض', nameEn: 'White Bread Loaf', price: 12, oldPrice: 15, categorySlug: 'bakery', emoji: '🍞', unit: 'رغيف', rating: 4.3, stock: 80, isOffer: true },
  { slug: 'chicken-breast-1kg', nameAr: 'صدور دجاج', nameEn: 'Chicken Breast', price: 145, oldPrice: 165, categorySlug: 'meat-poultry', emoji: '🍗', unit: '1 كجم', rating: 4.7, stock: 40, isOffer: true, isFeatured: true },
  { slug: 'coca-cola-1.5l', nameAr: 'كوكاكولا', nameEn: 'Coca-Cola', price: 22, oldPrice: 25, categorySlug: 'beverages', emoji: '🥤', unit: '1.5 لتر', rating: 4.9, stock: 150, isOffer: true },
  { slug: 'mineral-water-1.5l', nameAr: 'مياه معدنية', nameEn: 'Mineral Water', price: 8.5, oldPrice: null, categorySlug: 'beverages', emoji: '💧', unit: '1.5 لتر', rating: 4.5, stock: 300, isOffer: false },
  { slug: 'orange-juice-1l', nameAr: 'عصير برتقال', nameEn: 'Orange Juice', price: 35.99, oldPrice: 42, categorySlug: 'beverages', emoji: '🍊', unit: '1 لتر', rating: 4.4, stock: 60, isOffer: true },
  { slug: 'potatoes-1kg', nameAr: 'بطاطس', nameEn: 'Potatoes', price: 14.99, oldPrice: null, categorySlug: 'fruits-vegetables', emoji: '🥔', unit: '1 كجم', rating: 4.2, stock: 120, isOffer: false },
  { slug: 'bananas-1kg', nameAr: 'موز', nameEn: 'Bananas', price: 22.99, oldPrice: 28, categorySlug: 'fruits-vegetables', emoji: '🍌', unit: '1 كجم', rating: 4.6, stock: 90, isOffer: true, isFeatured: true },
  { slug: 'cucumber-1kg', nameAr: 'خيار', nameEn: 'Cucumber', price: 12.5, oldPrice: null, categorySlug: 'fruits-vegetables', emoji: '🥒', unit: '1 كجم', rating: 4.1, stock: 100, isOffer: false },
  { slug: 'apple-red-1kg', nameAr: 'تفاح أحمر', nameEn: 'Red Apples', price: 39.99, oldPrice: 49.99, categorySlug: 'fruits-vegetables', emoji: '🍎', unit: '1 كجم', rating: 4.5, stock: 70, isOffer: true },
  { slug: 'baby-diapers-size4', nameAr: 'حفاضات أطفال', nameEn: 'Baby Diapers', price: 249.99, oldPrice: 299.99, categorySlug: 'baby', emoji: '👶', unit: '56 حفاضة', rating: 4.8, stock: 30, isOffer: true },
  { slug: 'baby-formula-400g', nameAr: 'لبن أطفال', nameEn: 'Baby Formula', price: 189, oldPrice: null, categorySlug: 'baby', emoji: '🍼', unit: '400 جرام', rating: 4.7, stock: 25, isOffer: false, isFeatured: true },
  { slug: 'baby-wipes-80', nameAr: 'مناديل أطفال', nameEn: 'Baby Wipes', price: 45, oldPrice: 55, categorySlug: 'baby', emoji: '🧻', unit: '80 منديل', rating: 4.4, stock: 45, isOffer: true },
  { slug: 'bluetooth-earbuds', nameAr: 'سماعات بلوتوث', nameEn: 'Bluetooth Earbuds', price: 399.99, oldPrice: 549.99, categorySlug: 'electronics', emoji: '🎧', unit: 'قطعة', rating: 4.3, stock: 20, isOffer: true },
  { slug: 'usb-charger-20w', nameAr: 'شاحن USB 20W', nameEn: 'USB Charger 20W', price: 149.99, oldPrice: null, categorySlug: 'electronics', emoji: '🔌', unit: 'قطعة', rating: 4.5, stock: 35, isOffer: false },
  { slug: 'power-bank-10000', nameAr: 'باور بانك 10000', nameEn: 'Power Bank 10000mAh', price: 299, oldPrice: 399, categorySlug: 'electronics', emoji: '🔋', unit: 'قطعة', rating: 4.6, stock: 15, isOffer: true, isFeatured: true },
  { slug: 'dish-soap-750ml', nameAr: 'سائل أطباق', nameEn: 'Dish Soap', price: 28.5, oldPrice: null, categorySlug: 'cleaning', emoji: '🧴', unit: '750 مل', rating: 4.2, stock: 80, isOffer: false },
  { slug: 'laundry-detergent-3kg', nameAr: 'مسحوق غسيل', nameEn: 'Laundry Detergent', price: 119.99, oldPrice: 139.99, categorySlug: 'cleaning', emoji: '🧺', unit: '3 كجم', rating: 4.5, stock: 40, isOffer: true },
  { slug: 'chips-salt-170g', nameAr: 'شيبسي ملح', nameEn: 'Salt Chips', price: 15, oldPrice: null, categorySlug: 'snacks', emoji: '🍿', unit: '170 جرام', rating: 4, stock: 100, isOffer: false },
  { slug: 'chocolate-bar-100g', nameAr: 'شوكولاتة', nameEn: 'Chocolate Bar', price: 25, oldPrice: 32, categorySlug: 'snacks', emoji: '🍫', unit: '100 جرام', rating: 4.7, stock: 90, isOffer: true },
  { slug: 'shampoo-400ml', nameAr: 'شامبو', nameEn: 'Shampoo', price: 65, oldPrice: null, categorySlug: 'personal-care', emoji: '🧴', unit: '400 مل', rating: 4.3, stock: 55, isOffer: false },
  { slug: 'toothpaste-100ml', nameAr: 'معجون أسنان', nameEn: 'Toothpaste', price: 35.99, oldPrice: 42, categorySlug: 'personal-care', emoji: '🪥', unit: '100 مل', rating: 4.4, stock: 75, isOffer: true },
];
