import {
  LayoutDashboard,
  Package,
  PackageX,
  FolderOpen,
  ShoppingCart,
  Users,
  UserCog,
  Tag,
  Image,
  BarChart3,
  ScrollText,
  Settings,
  PanelsTopLeft,
  Star,
  Truck,
  Warehouse,
  Search,
  FileText,
  CreditCard,
  Bell,
  BellRing,
  Gift,
  MessageCircle,
  RotateCcw,
  Navigation,
  Palette,
  Radar,
  Radio,
  RefreshCw,
  Store,
  Trash2,
  ClipboardList,
  LineChart,
  SlidersHorizontal,
  Banknote,
  Flame,
  Award,
  Filter,
  Handshake,
  Wallet,
  Receipt,
  PhoneCall,
  Headphones,
} from 'lucide-react';

export const ADMIN_NAV_GROUPS = [
  {
    id: 'overview',
    labelAr: 'الرئيسية',
    labelEn: 'Overview',
    Icon: LayoutDashboard,
    items: [
      {
        path: '/admin',
        labelAr: 'لوحة التحكم',
        labelEn: 'Dashboard',
        Icon: LayoutDashboard,
        permission: 'dashboard:read',
      },
    ],
  },
  {
    id: 'catalog',
    labelAr: 'المتجر',
    labelEn: 'Store',
    Icon: Store,
    items: [
      { path: '/admin/products', labelAr: 'المنتجات', labelEn: 'Products', Icon: Package, permission: 'products:read' },
      {
        path: '/admin/stock-alerts',
        labelAr: 'تنبيهات المخزون',
        labelEn: 'Stock alerts',
        Icon: PackageX,
        badgeKey: 'outOfStockCount',
        permission: 'products:read',
      },
      { path: '/admin/categories', labelAr: 'الأقسام', labelEn: 'Categories', Icon: FolderOpen, permission: 'categories:write' },
      { path: '/admin/brands', labelAr: 'العلامات التجارية', labelEn: 'Brands', Icon: Award, permission: 'brands:write' },
      {
        path: '/admin/reviews',
        labelAr: 'التقييمات',
        labelEn: 'Reviews',
        Icon: Star,
        badgeKey: 'pendingReviews',
        permission: 'reviews:moderate',
      },
      { path: '/admin/coupons', labelAr: 'الكوبونات', labelEn: 'Coupons', Icon: Tag, permission: 'coupons:write' },
      { path: '/admin/promotions', labelAr: 'العروض والتخفيضات', labelEn: 'Offers & promotions', Icon: Flame, permission: 'promotions:write' },
      { path: '/admin/banners', labelAr: 'البانرات والحملات', labelEn: 'Banners & campaigns', Icon: Image, permission: 'banners:write' },
    ],
  },
  {
    id: 'orders',
    labelAr: 'الطلبات والتوصيل',
    labelEn: 'Orders & delivery',
    Icon: ClipboardList,
    items: [
      {
        path: '/admin/orders',
        labelAr: 'الطلبات',
        labelEn: 'Orders',
        Icon: ShoppingCart,
        badgeKey: 'pendingOrders',
        permission: 'orders:read',
      },
      {
        path: '/admin/invoices',
        labelAr: 'الفواتير',
        labelEn: 'Invoices',
        Icon: Receipt,
        permission: 'orders:read',
      },
      {
        path: '/admin/live-deliveries',
        labelAr: 'التوصيل المباشر',
        labelEn: 'Live deliveries',
        Icon: Radio,
        permission: 'orders:read',
      },
      {
        path: '/admin/recurring-deliveries',
        labelAr: 'التوصيل الدوري',
        labelEn: 'Recurring delivery',
        Icon: RefreshCw,
        permission: 'orders:read',
      },
      {
        path: '/admin/order-chats',
        labelAr: 'محادثة الطلبات',
        labelEn: 'Order chats',
        Icon: MessageCircle,
        badgeKey: 'unreadOrderMessages',
        permission: 'orders:read',
      },
      {
        path: '/admin/returns',
        labelAr: 'المرتجعات',
        labelEn: 'Returns',
        Icon: RotateCcw,
        badgeKey: 'pendingReturns',
        permission: 'orders:read',
      },
      {
        path: '/admin/callback-requests',
        labelAr: 'طلبات الاتصال',
        labelEn: 'Callback requests',
        Icon: PhoneCall,
        badgeKey: 'pendingCallbackRequests',
        permission: 'orders:read',
      },
      {
        path: '/admin/live-chat',
        labelAr: 'الدردشة المباشرة',
        labelEn: 'Live chat',
        Icon: MessageCircle,
        badgeKey: 'pendingLiveChats',
        permission: 'support:chat',
      },
      { path: '/admin/coverage-area', labelAr: 'منطقة التغطية', labelEn: 'Coverage area', Icon: Radar, permission: 'delivery:write' },
      { path: '/admin/delivery', labelAr: 'مناطق التوصيل', labelEn: 'Delivery zones', Icon: Truck, permission: 'delivery:write' },
      { path: '/admin/fulfillment-locations', labelAr: 'مواقع الشحن', labelEn: 'Fulfillment locations', Icon: Warehouse, permission: 'delivery:write' },
      {
        path: '/admin/order-trash',
        labelAr: 'سلة المحذوفات',
        labelEn: 'Recycle bin',
        Icon: Trash2,
        permission: 'orders:delete',
      },
    ],
  },
  {
    id: 'customers',
    labelAr: 'العملاء',
    labelEn: 'Customers',
    Icon: Users,
    items: [
      { path: '/admin/users', labelAr: 'المستخدمون', labelEn: 'Users', Icon: Users, permission: 'users:read' },
      { path: '/admin/team', labelAr: 'فريق الإدارة', labelEn: 'Admin team', Icon: UserCog, permission: 'users:write' },
      { path: '/admin/loyalty', labelAr: 'نقاط الولاء', labelEn: 'Loyalty points', Icon: Gift, permission: 'settings:write' },
      { path: '/admin/wallet', labelAr: 'المحافظ', labelEn: 'Wallets', Icon: Wallet, permission: 'settings:write' },
    ],
  },
  {
    id: 'content',
    labelAr: 'المحتوى وواجهة المتجر',
    labelEn: 'Content & storefront',
    Icon: PanelsTopLeft,
    items: [
      { path: '/admin/homepage', labelAr: 'Homepage CMS', labelEn: 'Homepage CMS', Icon: PanelsTopLeft, permission: 'homepage:write' },
      { path: '/admin/trending-searches', labelAr: 'الأكثر بحثاً', labelEn: 'Trending searches', Icon: Flame, permission: 'settings:write' },
      { path: '/admin/filter-settings', labelAr: 'إعدادات الفلاتر', labelEn: 'Filter settings', Icon: Filter, permission: 'settings:write' },
      { path: '/admin/navigation', labelAr: 'Header & Footer CMS', labelEn: 'Header & Footer CMS', Icon: Navigation, permission: 'settings:write' },
      { path: '/admin/content', labelAr: 'صفحات المحتوى', labelEn: 'Content pages', Icon: FileText, permission: 'content:write' },
      { path: '/admin/appearance', labelAr: 'المظهر والألوان', labelEn: 'Appearance', Icon: Palette, permission: 'settings:write' },
    ],
  },
  {
    id: 'analytics',
    labelAr: 'التقارير والتحليلات',
    labelEn: 'Analytics',
    Icon: LineChart,
    items: [
      {
        path: '/admin/revenue',
        labelAr: 'الإيرادات',
        labelEn: 'Revenue',
        Icon: Banknote,
        permission: 'reports:read',
        requiresRevenue: true,
      },
      {
        path: '/admin/reports',
        labelAr: 'التقارير',
        labelEn: 'Reports',
        Icon: BarChart3,
        permission: 'reports:read',
        requiresRevenue: true,
      },
      {
        path: '/admin/partner-revenue',
        labelAr: 'توزيع إيرادات الشركاء',
        labelEn: 'Partner revenue',
        Icon: Handshake,
        permission: 'reports:read',
        requiresRevenue: true,
      },
      { path: '/admin/search-analytics', labelAr: 'تحليلات البحث', labelEn: 'Search analytics', Icon: Search, permission: 'reports:read' },
    ],
  },
  {
    id: 'settings',
    labelAr: 'الإعدادات',
    labelEn: 'Settings',
    Icon: SlidersHorizontal,
    items: [
      { path: '/admin/settings', labelAr: 'إعدادات المتجر', labelEn: 'Store settings', Icon: Settings, permission: 'settings:write' },
      { path: '/admin/payments', labelAr: 'طرق الدفع', labelEn: 'Payment methods', Icon: CreditCard, permission: 'settings:write' },
      { path: '/admin/customer-service', labelAr: 'خدمة العملاء', labelEn: 'Customer service', Icon: Headphones, permission: 'settings:write' },
      { path: '/admin/notifications', labelAr: 'قوالب الإشعارات', labelEn: 'Notification templates', Icon: Bell, permission: 'notifications:write' },
      { path: '/admin/push', labelAr: 'إشعارات التطبيق', labelEn: 'App push notifications', Icon: BellRing, permission: 'notifications:write' },
      { path: '/admin/audit-log', labelAr: 'سجل التدقيق', labelEn: 'Audit log', Icon: ScrollText, permission: 'audit:read' },
    ],
  },
];

export const ADMIN_NAV = ADMIN_NAV_GROUPS.flatMap((group) => group.items);
