import { mergeFreeDeliveryBanner, parseFreeDeliveryMethodsFromApi } from '../../utils/freeDelivery';

/** Keep in sync with DEFAULT_DRIVER_SETTINGS (backend/src/constants/storeDefaults.js). */
export const DEFAULT_DRIVER_SETTINGS = {
  autoAssignEnabled: false,
  autoAssignMaxActive: 0,
  availabilityEnabled: true,
  pickingChecklistEnabled: true,
  cashCalculatorEnabled: true,
};

export function normalizeDriverSettings(raw = {}) {
  const data = raw || {};
  const maxActive = Math.round(Number(data.autoAssignMaxActive));
  return {
    autoAssignEnabled: data.autoAssignEnabled === true,
    autoAssignMaxActive: Number.isFinite(maxActive) ? Math.min(50, Math.max(0, maxActive)) : 0,
    availabilityEnabled: data.availabilityEnabled !== false,
    pickingChecklistEnabled: data.pickingChecklistEnabled !== false,
    cashCalculatorEnabled: data.cashCalculatorEnabled !== false,
  };
}

/** Keep in sync with DEFAULT_LOCATION_GATE (backend/src/constants/storeDefaults.js). */
export const DEFAULT_LOCATION_GATE = {
  enabled: false,
  mandatory: true,
  enforceCoverage: true,
  titleAr: 'اختر منطقتك',
  titleEn: 'Choose your area',
  subtitleAr: 'حدّد منطقة التوصيل لعرض المنتجات والأسعار ومواعيد التوصيل الصحيحة',
  subtitleEn: 'Set your delivery area to see the right products, prices and delivery slots',
  mapCenterLat: 29.8453,
  mapCenterLng: 31.3339,
  mapZoom: 12,
};

export function normalizeLocationGate(raw = {}) {
  const data = raw || {};
  const num = (value, fallback) => {
    const n = Number(value);
    return Number.isFinite(n) ? n : fallback;
  };
  return {
    enabled: data.enabled === true,
    mandatory: data.mandatory !== false,
    enforceCoverage: data.enforceCoverage !== false,
    titleAr: data.titleAr ?? DEFAULT_LOCATION_GATE.titleAr,
    titleEn: data.titleEn ?? DEFAULT_LOCATION_GATE.titleEn,
    subtitleAr: data.subtitleAr ?? DEFAULT_LOCATION_GATE.subtitleAr,
    subtitleEn: data.subtitleEn ?? DEFAULT_LOCATION_GATE.subtitleEn,
    mapCenterLat: num(data.mapCenterLat, DEFAULT_LOCATION_GATE.mapCenterLat),
    mapCenterLng: num(data.mapCenterLng, DEFAULT_LOCATION_GATE.mapCenterLng),
    mapZoom: Math.round(num(data.mapZoom, DEFAULT_LOCATION_GATE.mapZoom)),
  };
}

export const emptyStoreSettings = {
  storeNameAr: '',
  storeNameEn: '',
  taglineAr: '',
  taglineEn: '',
  logoUrl: '',
  faviconUrl: '',
  supportPhone: '',
  supportEmail: '',
  whatsappUrl: '',
  defaultLocationAr: '',
  defaultLocationEn: '',
  deliveryPromiseAr: '',
  deliveryPromiseEn: '',
  cartToastAddedAr: '',
  cartToastAddedEn: '',
  lowStockAlertEnabled: true,
  lowStockAlertThreshold: 10,
  lowStockMessageAr: 'باقي {{qty}} فقط',
  lowStockMessageEn: 'Only {{qty}} left',
  reviewSettings: {
    autoRequestOnDelivered: true,
    requestSms: true,
    requestEmail: true,
  },
  freeDeliveryThreshold: 0,
  freeDeliveryEnabled: true,
  gpsDeliveryEnabled: true,
  aiChatEnabled: true,
  locationGate: { ...DEFAULT_LOCATION_GATE },
  driverSettings: { ...DEFAULT_DRIVER_SETTINGS },
  freeDeliveryMethods: ['scheduled', 'recurring'],
  freeDeliveryBanner: mergeFreeDeliveryBanner(),
  scheduledMinLeadMinutes: 120,
  expressMinLeadMinutes: 120,
  currency: 'EGP',
  socialLinks: {
    facebook: '',
    instagram: '',
    x: '',
    youtube: '',
  },
  appLinks: {
    appStore: '',
    googlePlay: '',
    appGallery: '',
  },
  loyalty: {
    enabled: true,
    earnPointsPerEGP: 0.1,
    redemptionEGPPerPoint: 0.1,
    expiryDays: 365,
    minOrderToEarn: 100,
    minRedeemPoints: 100,
    maxRedeemPercent: 50,
  },
  isActive: true,
  adminPanel: {
    showRevenue: true,
  },
  invoice: {
    titleAr: 'فاتورة ضريبية',
    titleEn: 'Tax Invoice',
    documentPrefixAr: '',
    documentPrefixEn: '',
    companyNameAr: 'سوق+ للتجارة',
    companyNameEn: 'MarketPlus Retail',
    companyAddressAr: 'شارع التحرير، مدينة نصر، القاهرة، مصر',
    companyAddressEn: 'Tahrir Street, Nasr City, Cairo, Egypt',
    taxRegistrationNumber: '123-456-789',
    taxIdLabelAr: 'الرقم الضريبي',
    taxIdLabelEn: 'Tax ID',
    paymentMethodLabelAr: 'طريقة الدفع',
    paymentMethodLabelEn: 'Payment method',
    headerNoteAr: 'شكراً لاختياركم سوق+ — نتمنى لكم تسوقاً ممتعاً',
    headerNoteEn: 'Thank you for choosing MarketPlus — happy shopping!',
    footerNoteAr: 'للاستفسارات: اتصل بنا على الرقم الموضح أعلاه',
    footerNoteEn: 'For questions, call the support number shown above.',
    termsAr: 'هذه فاتورة إلكترونية صادرة من نظام سوق+ ولا تحتاج إلى توقيع أو ختم.',
    termsEn: 'This is an electronic invoice issued by MarketPlus and does not require a signature or stamp.',
    bankDetailsAr: '',
    bankDetailsEn: '',
    accentColor: '#0f766e',
    pageSize: 'A4',
    logoPosition: 'end',
    logoSize: 'md',
    showLogo: true,
    showTaxId: true,
    showOrderStatus: true,
    showPaymentStatus: true,
    showPaymentMethod: true,
    showSavings: true,
    showBankDetails: false,
    showStamp: false,
    showQr: false,
    stampUrl: '',
    columns: { sku: false, unitPrice: true, lineTotal: true },
    customRows: [],
    labels: {
      invoiceAr: 'فاتورة',
      invoiceEn: 'Invoice',
      orderNumberAr: 'رقم الطلب',
      orderNumberEn: 'Order no.',
      dateAr: 'التاريخ',
      dateEn: 'Date',
      customerAr: 'بيانات العميل',
      customerEn: 'Customer',
      itemsAr: 'المنتجات',
      itemsEn: 'Items',
      itemAr: 'المنتج',
      itemEn: 'Product',
      qtyAr: 'الكمية',
      qtyEn: 'Qty',
      priceAr: 'السعر',
      priceEn: 'Price',
      lineTotalAr: 'المجموع',
      lineTotalEn: 'Total',
      subtotalAr: 'المجموع الفرعي',
      subtotalEn: 'Subtotal',
      deliveryAr: 'التوصيل',
      deliveryEn: 'Delivery',
      discountAr: 'الخصم',
      discountEn: 'Discount',
      pointsDiscountAr: 'خصم النقاط',
      pointsDiscountEn: 'Points discount',
      grandTotalAr: 'الإجمالي',
      grandTotalEn: 'Grand total',
      orderStatusAr: 'حالة الطلب',
      orderStatusEn: 'Order status',
      paymentStatusAr: 'حالة الدفع',
      paymentStatusEn: 'Payment status',
      phoneAr: 'الهاتف',
      phoneEn: 'Phone',
    },
  },
};

export function normalizeStoreSettings(data = {}) {
  return {
    ...emptyStoreSettings,
    ...data,
    socialLinks: { ...emptyStoreSettings.socialLinks, ...(data.socialLinks || {}) },
    appLinks: { ...emptyStoreSettings.appLinks, ...(data.appLinks || {}) },
    loyalty: { ...emptyStoreSettings.loyalty, ...(data.loyalty || {}) },
    invoice: {
      ...emptyStoreSettings.invoice,
      ...(data.invoice || {}),
      labels: { ...emptyStoreSettings.invoice.labels, ...(data.invoice?.labels || {}) },
      columns: { ...emptyStoreSettings.invoice.columns, ...(data.invoice?.columns || {}) },
      customRows: Array.isArray(data.invoice?.customRows) ? data.invoice.customRows : [],
    },
    freeDeliveryThreshold: data.freeDeliveryThreshold ?? 0,
    freeDeliveryEnabled: data.freeDeliveryEnabled !== false,
    gpsDeliveryEnabled: data.gpsDeliveryEnabled !== false,
    aiChatEnabled: data.aiChatEnabled !== false,
    locationGate: normalizeLocationGate(data.locationGate),
    driverSettings: normalizeDriverSettings(data.driverSettings),
    freeDeliveryMethods: parseFreeDeliveryMethodsFromApi(data.freeDeliveryMethods),
    freeDeliveryBanner: mergeFreeDeliveryBanner(data.freeDeliveryBanner),
    scheduledMinLeadMinutes: Number(data.scheduledMinLeadMinutes) || 120,
    expressMinLeadMinutes: Number(data.expressMinLeadMinutes) || 120,
    cartToastAddedAr: data.cartToastAddedAr ?? emptyStoreSettings.cartToastAddedAr,
    cartToastAddedEn: data.cartToastAddedEn ?? emptyStoreSettings.cartToastAddedEn,
    lowStockAlertEnabled: data.lowStockAlertEnabled !== false,
    lowStockAlertThreshold: Number(data.lowStockAlertThreshold) || 10,
    lowStockMessageAr: data.lowStockMessageAr ?? emptyStoreSettings.lowStockMessageAr,
    lowStockMessageEn: data.lowStockMessageEn ?? emptyStoreSettings.lowStockMessageEn,
    reviewSettings: {
      autoRequestOnDelivered: data.reviewSettings?.autoRequestOnDelivered !== false,
      requestSms: data.reviewSettings?.requestSms !== false,
      requestEmail: data.reviewSettings?.requestEmail !== false,
    },
    isActive: data.isActive !== false,
    adminPanel: {
      showRevenue: data.adminPanel?.showRevenue !== false,
    },
  };
}
