import { mergeFreeDeliveryBanner, parseFreeDeliveryMethodsFromApi } from '../../utils/freeDelivery';
import { normalizeLocationGate, normalizeDriverSettings, normalizeCustomerService, normalizeLiveChatSettings } from './storeSettingsDefaults';

/** Build a clean payload for store settings save (no Mongo metadata). */
export function buildStoreSettingsSavePayload(settings) {
  return {
    storeNameAr: settings.storeNameAr ?? '',
    storeNameEn: settings.storeNameEn ?? '',
    taglineAr: settings.taglineAr ?? '',
    taglineEn: settings.taglineEn ?? '',
    logoUrl: settings.logoUrl ?? '',
    faviconUrl: settings.faviconUrl ?? '',
    supportPhone: settings.supportPhone ?? '',
    supportEmail: settings.supportEmail ?? '',
    whatsappUrl: settings.whatsappUrl ?? '',
    defaultLocationAr: settings.defaultLocationAr ?? '',
    defaultLocationEn: settings.defaultLocationEn ?? '',
    deliveryPromiseAr: settings.deliveryPromiseAr ?? '',
    deliveryPromiseEn: settings.deliveryPromiseEn ?? '',
    cartToastAddedAr: settings.cartToastAddedAr ?? '',
    cartToastAddedEn: settings.cartToastAddedEn ?? '',
    lowStockAlertEnabled: settings.lowStockAlertEnabled !== false,
    lowStockAlertThreshold: Math.max(1, Math.round(Number(settings.lowStockAlertThreshold) || 10)),
    adminStockAlertThreshold: Math.max(0, Math.round(Number(settings.adminStockAlertThreshold) || 10)),
    lowStockMessageAr: settings.lowStockMessageAr ?? 'باقي {{qty}} فقط',
    lowStockMessageEn: settings.lowStockMessageEn ?? 'Only {{qty}} left',
    reviewSettings: {
      autoRequestOnDelivered: settings.reviewSettings?.autoRequestOnDelivered !== false,
      requestSms: settings.reviewSettings?.requestSms !== false,
      requestEmail: settings.reviewSettings?.requestEmail !== false,
    },
    freeDeliveryThreshold: Number(settings.freeDeliveryThreshold) || 0,
    freeDeliveryEnabled: settings.freeDeliveryEnabled !== false,
    gpsDeliveryEnabled: settings.gpsDeliveryEnabled !== false,
    aiChatEnabled: settings.aiChatEnabled !== false,
    locationGate: normalizeLocationGate(settings.locationGate),
    driverSettings: normalizeDriverSettings(settings.driverSettings),
    customerService: normalizeCustomerService(settings.customerService),
    liveChat: normalizeLiveChatSettings(settings.liveChat),
    freeDeliveryMethods: parseFreeDeliveryMethodsFromApi(settings.freeDeliveryMethods),
    freeDeliveryBanner: mergeFreeDeliveryBanner(settings.freeDeliveryBanner),
    scheduledMinLeadMinutes: Math.min(1440, Math.max(0, Math.round(Number(settings.scheduledMinLeadMinutes) || 120))),
    expressMinLeadMinutes: Math.min(1440, Math.max(0, Math.round(Number(settings.expressMinLeadMinutes) || 120))),
    currency: settings.currency ?? 'EGP',
    socialLinks: settings.socialLinks ?? {},
    appLinks: settings.appLinks ?? {},
    loyalty: {
      ...(settings.loyalty || {}),
      earnPointsPerEGP: Number(settings.loyalty?.earnPointsPerEGP) || 0,
      redemptionEGPPerPoint: Number(settings.loyalty?.redemptionEGPPerPoint) || 0,
      expiryDays: Number(settings.loyalty?.expiryDays) || 0,
      minOrderToEarn: Number(settings.loyalty?.minOrderToEarn) || 0,
      minRedeemPoints: Number(settings.loyalty?.minRedeemPoints) || 0,
      maxRedeemPercent: Number(settings.loyalty?.maxRedeemPercent) || 0,
    },
    navigation: settings.navigation,
    seo: settings.seo,
    paymentMethods: settings.paymentMethods,
    searchSettings: settings.searchSettings,
    adminPanel: settings.adminPanel ?? { showRevenue: true },
    invoice: settings.invoice,
    themeColor: settings.themeColor ?? 'green',
    themeShade: Number(settings.themeShade) || 600,
    themeRotation: settings.themeRotation ?? { enabled: false, intervalMinutes: 30, steps: [] },
    siteFont: settings.siteFont ?? 'cairo',
    isActive: settings.isActive !== false,
  };
}
