import { mergeFreeDeliveryBanner, parseFreeDeliveryMethodsFromApi } from '../../utils/freeDelivery';

export const emptyStoreSettings = {
  storeNameAr: '',
  storeNameEn: '',
  taglineAr: '',
  taglineEn: '',
  logoUrl: '',
  faviconUrl: '',
  supportPhone: '',
  supportEmail: '',
  whatsappUrl: '',
  defaultLocationAr: '',
  defaultLocationEn: '',
  deliveryPromiseAr: '',
  deliveryPromiseEn: '',
  cartToastAddedAr: '',
  cartToastAddedEn: '',
  lowStockAlertEnabled: true,
  lowStockAlertThreshold: 10,
  lowStockMessageAr: 'باقي {{qty}} فقط',
  lowStockMessageEn: 'Only {{qty}} left',
  reviewSettings: {
    autoRequestOnDelivered: true,
    requestSms: true,
    requestEmail: true,
  },
  freeDeliveryThreshold: 0,
  freeDeliveryEnabled: true,
  gpsDeliveryEnabled: true,
  aiChatEnabled: true,
  freeDeliveryMethods: ['scheduled', 'recurring'],
  freeDeliveryBanner: mergeFreeDeliveryBanner(),
  scheduledMinLeadMinutes: 120,
  expressMinLeadMinutes: 120,
  currency: 'EGP',
  socialLinks: {
    facebook: '',
    instagram: '',
    x: '',
    youtube: '',
  },
  appLinks: {
    appStore: '',
    googlePlay: '',
    appGallery: '',
  },
  loyalty: {
    enabled: true,
    earnPointsPerEGP: 0.1,
    redemptionEGPPerPoint: 0.1,
    expiryDays: 365,
    minOrderToEarn: 100,
    minRedeemPoints: 100,
    maxRedeemPercent: 50,
  },
  isActive: true,
  adminPanel: {
    showRevenue: true,
  },
  invoice: {
    titleAr: 'فاتورة ضريبية',
    titleEn: 'Tax Invoice',
    companyNameAr: 'سوق+ للتجارة',
    companyNameEn: 'MarketPlus Retail',
    companyAddressAr: 'شارع التحرير، مدينة نصر، القاهرة، مصر',
    companyAddressEn: 'Tahrir Street, Nasr City, Cairo, Egypt',
    taxRegistrationNumber: '123-456-789',
    taxIdLabelAr: 'الرقم الضريبي',
    taxIdLabelEn: 'Tax ID',
    headerNoteAr: 'شكراً لاختياركم سوق+ — نتمنى لكم تسوقاً ممتعاً',
    headerNoteEn: 'Thank you for choosing MarketPlus — happy shopping!',
    footerNoteAr: 'للاستفسارات: اتصل بنا على الرقم الموضح أعلاه',
    footerNoteEn: 'For questions, call the support number shown above.',
    termsAr: 'هذه فاتورة إلكترونية صادرة من نظام سوق+ ولا تحتاج إلى توقيع أو ختم.',
    termsEn: 'This is an electronic invoice issued by MarketPlus and does not require a signature or stamp.',
    showLogo: true,
    showTaxId: true,
    showOrderStatus: true,
    showPaymentStatus: true,
    labels: {
      invoiceAr: 'فاتورة',
      invoiceEn: 'Invoice',
      orderNumberAr: 'رقم الطلب',
      orderNumberEn: 'Order no.',
      dateAr: 'التاريخ',
      dateEn: 'Date',
      customerAr: 'بيانات العميل',
      customerEn: 'Customer',
      itemsAr: 'المنتجات',
      itemsEn: 'Items',
      itemAr: 'المنتج',
      itemEn: 'Product',
      qtyAr: 'الكمية',
      qtyEn: 'Qty',
      priceAr: 'السعر',
      priceEn: 'Price',
      lineTotalAr: 'المجموع',
      lineTotalEn: 'Total',
      subtotalAr: 'المجموع الفرعي',
      subtotalEn: 'Subtotal',
      deliveryAr: 'التوصيل',
      deliveryEn: 'Delivery',
      discountAr: 'الخصم',
      discountEn: 'Discount',
      pointsDiscountAr: 'خصم النقاط',
      pointsDiscountEn: 'Points discount',
      grandTotalAr: 'الإجمالي',
      grandTotalEn: 'Grand total',
      orderStatusAr: 'حالة الطلب',
      orderStatusEn: 'Order status',
      paymentStatusAr: 'حالة الدفع',
      paymentStatusEn: 'Payment status',
      phoneAr: 'الهاتف',
      phoneEn: 'Phone',
    },
  },
};

export function normalizeStoreSettings(data = {}) {
  return {
    ...emptyStoreSettings,
    ...data,
    socialLinks: { ...emptyStoreSettings.socialLinks, ...(data.socialLinks || {}) },
    appLinks: { ...emptyStoreSettings.appLinks, ...(data.appLinks || {}) },
    loyalty: { ...emptyStoreSettings.loyalty, ...(data.loyalty || {}) },
    invoice: {
      ...emptyStoreSettings.invoice,
      ...(data.invoice || {}),
      labels: { ...emptyStoreSettings.invoice.labels, ...(data.invoice?.labels || {}) },
    },
    freeDeliveryThreshold: data.freeDeliveryThreshold ?? 0,
    freeDeliveryEnabled: data.freeDeliveryEnabled !== false,
    gpsDeliveryEnabled: data.gpsDeliveryEnabled !== false,
    aiChatEnabled: data.aiChatEnabled !== false,
    freeDeliveryMethods: parseFreeDeliveryMethodsFromApi(data.freeDeliveryMethods),
    freeDeliveryBanner: mergeFreeDeliveryBanner(data.freeDeliveryBanner),
    scheduledMinLeadMinutes: Number(data.scheduledMinLeadMinutes) || 120,
    expressMinLeadMinutes: Number(data.expressMinLeadMinutes) || 120,
    cartToastAddedAr: data.cartToastAddedAr ?? emptyStoreSettings.cartToastAddedAr,
    cartToastAddedEn: data.cartToastAddedEn ?? emptyStoreSettings.cartToastAddedEn,
    lowStockAlertEnabled: data.lowStockAlertEnabled !== false,
    lowStockAlertThreshold: Number(data.lowStockAlertThreshold) || 10,
    lowStockMessageAr: data.lowStockMessageAr ?? emptyStoreSettings.lowStockMessageAr,
    lowStockMessageEn: data.lowStockMessageEn ?? emptyStoreSettings.lowStockMessageEn,
    reviewSettings: {
      autoRequestOnDelivered: data.reviewSettings?.autoRequestOnDelivered !== false,
      requestSms: data.reviewSettings?.requestSms !== false,
      requestEmail: data.reviewSettings?.requestEmail !== false,
    },
    isActive: data.isActive !== false,
    adminPanel: {
      showRevenue: data.adminPanel?.showRevenue !== false,
    },
  };
}
