export const NOTIFICATION_TEMPLATE_KEYS = [
  'order_confirmation',
  'payment_success',
  'order_status_update',
  'admin_new_order',
  'order_sms_created',
  'order_sms_confirmed',
  'order_sms_preparing',
  'order_sms_out_for_delivery',
  'order_sms_delivered',
  'order_sms_cancelled',
  'order_sms_refunded',
  'order_sms_substitution',
  'order_sms_review_request',
  'order_sms_tracking_live',
  'order_sms_driver_assigned',
  'order_sms_driver_location',
  'order_sms_driver_nearby',
  'review_request_email',
];

export const DEFAULT_NOTIFICATION_TEMPLATES = [
  {
    key: 'order_confirmation',
    nameAr: 'تأكيد الطلب',
    nameEn: 'Order confirmation',
    channel: 'email',
    subjectAr: 'تأكيد الطلب {{order.orderNumber}} — سوق+',
    subjectEn: 'Order {{order.orderNumber}} confirmed — MarketPlus',
    bodyHtmlAr: '<p>مرحباً <strong>{{user.name}}</strong>،</p><p>تم استلام طلبك {{order.orderNumber}} بنجاح.</p>',
    bodyHtmlEn: '<p>Hi <strong>{{user.name}}</strong>,</p><p>Your order {{order.orderNumber}} was received.</p>',
    bodyTextAr: 'تم تأكيد طلبك {{order.orderNumber}}',
    bodyTextEn: 'Your order {{order.orderNumber}} was confirmed',
    placeholders: ['user.name', 'order.orderNumber', 'order.total'],
    isActive: true,
  },
  {
    key: 'payment_success',
    nameAr: 'نجاح الدفع',
    nameEn: 'Payment success',
    channel: 'email',
    subjectAr: 'تم الدفع بنجاح — {{order.orderNumber}}',
    subjectEn: 'Payment received — {{order.orderNumber}}',
    bodyHtmlAr: '<p>تم استلام دفعتك للطلب {{order.orderNumber}}.</p>',
    bodyHtmlEn: '<p>Payment received for order {{order.orderNumber}}.</p>',
    bodyTextAr: 'تم الدفع للطلب {{order.orderNumber}}',
    bodyTextEn: 'Payment received for {{order.orderNumber}}',
    placeholders: ['order.orderNumber', 'order.total'],
    isActive: true,
  },
  {
    key: 'order_status_update',
    nameAr: 'تحديث حالة الطلب',
    nameEn: 'Order status update',
    channel: 'email',
    subjectAr: 'تحديث الطلب {{order.orderNumber}}: {{statusLabel}}',
    subjectEn: 'Order {{order.orderNumber}} update: {{statusLabel}}',
    bodyHtmlAr: '<p>تم تحديث حالة طلبك {{order.orderNumber}} إلى {{statusLabel}}.</p>',
    bodyHtmlEn: '<p>Your order {{order.orderNumber}} is now {{statusLabel}}.</p>',
    bodyTextAr: 'تحديث الطلب {{order.orderNumber}}',
    bodyTextEn: 'Order {{order.orderNumber}} updated',
    placeholders: ['order.orderNumber', 'statusLabel', 'user.name'],
    isActive: true,
  },
  {
    key: 'admin_new_order',
    nameAr: 'طلب جديد (إدارة)',
    nameEn: 'New order (admin)',
    channel: 'email',
    subjectAr: '[سوق+] طلب جديد {{order.orderNumber}}',
    subjectEn: '[MarketPlus] New order {{order.orderNumber}}',
    bodyHtmlAr: '<p>طلب جديد من {{user.name}} — {{order.orderNumber}}</p>',
    bodyHtmlEn: '<p>New order from {{user.name}} — {{order.orderNumber}}</p>',
    bodyTextAr: 'طلب جديد {{order.orderNumber}}',
    bodyTextEn: 'New order {{order.orderNumber}}',
    placeholders: ['order.orderNumber', 'user.name', 'order.total'],
    isActive: true,
  },
  {
    key: 'order_sms_created',
    nameAr: 'SMS — استلام الطلب',
    nameEn: 'SMS — order received',
    channel: 'sms',
    smsBodyAr: 'سوق+: تم استلام طلبك {{order.orderNumber}}. الإجمالي {{order.total}} ج.م.',
    smsBodyEn: 'MarketPlus: Order {{order.orderNumber}} received. Total {{order.total}} EGP.',
    placeholders: ['order.orderNumber', 'order.total'],
    isActive: true,
  },
  {
    key: 'order_sms_confirmed',
    nameAr: 'SMS — تأكيد الطلب',
    nameEn: 'SMS — order confirmed',
    channel: 'sms',
    smsBodyAr: 'سوق+: تم تأكيد طلبك {{order.orderNumber}} وجاري تجهيزه.',
    smsBodyEn: 'MarketPlus: Order {{order.orderNumber}} confirmed.',
    placeholders: ['order.orderNumber'],
    isActive: true,
  },
  {
    key: 'order_sms_preparing',
    nameAr: 'SMS — التجهيز',
    nameEn: 'SMS — preparing',
    channel: 'sms',
    smsBodyAr: 'سوق+: طلبك {{order.orderNumber}} قيد التجهيز الآن.',
    smsBodyEn: 'MarketPlus: Order {{order.orderNumber}} is being prepared.',
    placeholders: ['order.orderNumber'],
    isActive: true,
  },
  {
    key: 'order_sms_out_for_delivery',
    nameAr: 'SMS — في الطريق',
    nameEn: 'SMS — out for delivery',
    channel: 'sms',
    smsBodyAr: 'سوق+: طلبك {{order.orderNumber}} في الطريق إليك!',
    smsBodyEn: 'MarketPlus: Order {{order.orderNumber}} is out for delivery!',
    placeholders: ['order.orderNumber'],
    isActive: true,
  },
  {
    key: 'order_sms_delivered',
    nameAr: 'SMS — تم التسليم',
    nameEn: 'SMS — delivered',
    channel: 'sms',
    smsBodyAr: 'سوق+: تم تسليم طلبك {{order.orderNumber}}. نتمنى لك تسوقاً سعيداً!',
    smsBodyEn: 'MarketPlus: Order {{order.orderNumber}} delivered. Enjoy!',
    placeholders: ['order.orderNumber'],
    isActive: true,
  },
  {
    key: 'order_sms_cancelled',
    nameAr: 'SMS — إلغاء',
    nameEn: 'SMS — cancelled',
    channel: 'sms',
    smsBodyAr: 'سوق+: تم إلغاء طلبك {{order.orderNumber}}.',
    smsBodyEn: 'MarketPlus: Order {{order.orderNumber}} cancelled.',
    placeholders: ['order.orderNumber'],
    isActive: true,
  },
  {
    key: 'order_sms_refunded',
    nameAr: 'SMS — استرداد',
    nameEn: 'SMS — refunded',
    channel: 'sms',
    smsBodyAr: 'سوق+: تم استرداد {{order.refundAmount}} ج.م للطلب {{order.orderNumber}}.',
    smsBodyEn: 'MarketPlus: Refund of {{order.refundAmount}} EGP for order {{order.orderNumber}}.',
    placeholders: ['order.orderNumber', 'order.refundAmount'],
    isActive: true,
  },
  {
    key: 'order_sms_substitution',
    nameAr: 'SMS — بديل',
    nameEn: 'SMS — substitution',
    channel: 'sms',
    smsBodyAr: 'سوق+: يوجد اقتراح بديل لطلبك {{order.orderNumber}}. راجع التطبيق.',
    smsBodyEn: 'MarketPlus: Substitution suggested for order {{order.orderNumber}}.',
    placeholders: ['order.orderNumber'],
    isActive: true,
  },
  {
    key: 'order_sms_review_request',
    nameAr: 'SMS — طلب تقييم بعد التسليم',
    nameEn: 'SMS — review request after delivery',
    channel: 'sms',
    smsBodyAr: 'سوق+: تم تسليم طلبك {{order.orderNumber}}. شاركنا رأيك في المنتجات من صفحة طلباتي ⭐',
    smsBodyEn: 'MarketPlus: Order {{order.orderNumber}} delivered. Rate your items in My Orders ⭐',
    placeholders: ['order.orderNumber'],
    isActive: true,
  },
  {
    key: 'order_sms_tracking_live',
    nameAr: 'SMS — رابط التتبع المباشر',
    nameEn: 'SMS — live tracking link',
    channel: 'sms',
    smsBodyAr: 'سوق+: تتبع طلبك {{order.orderNumber}} مباشرة على الخريطة: {{trackUrl}}',
    smsBodyEn: 'MarketPlus: Track order {{order.orderNumber}} live: {{trackUrl}}',
    placeholders: ['order.orderNumber', 'trackUrl'],
    isActive: true,
  },
  {
    key: 'order_sms_driver_assigned',
    nameAr: 'SMS — تعيين مندوب',
    nameEn: 'SMS — driver assigned',
    channel: 'sms',
    smsBodyAr: 'سوق+: تم تعيين مندوب لطلبك {{order.orderNumber}}. تتبع التوصيل: {{trackUrl}}',
    smsBodyEn: 'MarketPlus: A driver is assigned to order {{order.orderNumber}}. Track: {{trackUrl}}',
    placeholders: ['order.orderNumber', 'trackUrl', 'driverName'],
    isActive: true,
  },
  {
    key: 'order_sms_driver_location',
    nameAr: 'SMS — تحديث موقع المندوب',
    nameEn: 'SMS — driver location update',
    channel: 'sms',
    smsBodyAr: 'سوق+: المندوب في الطريق لطلبك {{order.orderNumber}}. تتبع: {{trackUrl}}',
    smsBodyEn: 'MarketPlus: Driver en route for order {{order.orderNumber}}. Track: {{trackUrl}}',
    placeholders: ['order.orderNumber', 'trackUrl', 'etaText'],
    isActive: true,
  },
  {
    key: 'order_sms_driver_nearby',
    nameAr: 'SMS — المندوب قريب',
    nameEn: 'SMS — driver nearby',
    channel: 'sms',
    smsBodyAr: 'سوق+: مندوب طلبك {{order.orderNumber}} على وشك الوصول!',
    smsBodyEn: 'MarketPlus: Your driver for order {{order.orderNumber}} is almost there!',
    placeholders: ['order.orderNumber', 'etaText'],
    isActive: true,
  },
  {
    key: 'review_request_email',
    nameAr: 'بريد — طلب تقييم',
    nameEn: 'Email — review request',
    channel: 'email',
    subjectAr: 'قيّم طلبك {{order.orderNumber}} — سوق+',
    subjectEn: 'Rate order {{order.orderNumber}} — MarketPlus',
    bodyHtmlAr: '<p>مرحباً <strong>{{user.name}}</strong>،</p><p>تم تسليم طلبك {{order.orderNumber}}. نود معرفة رأيك في المنتجات.</p>',
    bodyHtmlEn: '<p>Hi <strong>{{user.name}}</strong>,</p><p>Your order {{order.orderNumber}} was delivered. Please rate your items.</p>',
    bodyTextAr: 'تم تسليم طلبك {{order.orderNumber}}. قيّم مشترياتك من صفحة طلباتي.',
    bodyTextEn: 'Order {{order.orderNumber}} delivered. Rate your items in My Orders.',
    placeholders: ['order.orderNumber', 'user.name'],
    isActive: true,
  },
];
